import styles from "./styles.module.scss"

export const EmojiCard = () => {

    return <div className={styles.EmojiCard}>
        <button>😀</button>
        <button>😃</button>
        <button>😄</button>
        <button>😁</button>
        <button>😆</button>
        <button>😅</button>
        <button>😂</button>
        <button>🤣</button>
        <button>🥲</button>
        <button>🥹</button>
        <button>☺️</button>
        <button>😊</button>
        <button>😇</button>
        <button>🙂</button>
        <button>🙃</button>
        <button>😉</button>
        <button>😌</button>
        <button>😍</button>
        <button>🥰</button>
        <button>😘</button>
        <button>😗</button>
        <button>😙</button>
        <button>😚</button>
        <button>😋</button>
        <button>😛</button>
        <button>😝</button>
        <button>😜</button>
        <button>🤪</button>
        <button>🤨</button>
        <button>🧐</button>
        <button>🤓</button>
        <button>😎</button>
        <button>🥸</button>
        <button>🤩</button>
        <button>🥳</button>
        <button>😏</button>
        <button>😒</button>
        <button>😞</button>
        <button>😔</button>
        <button>😟</button>
        <button>😕</button>
        <button>🙁</button>
        <button>☹️</button>
        <button>😣</button>
        <button>😖</button>
        <button>😫</button>
        <button>😩</button>
        <button>🥺</button>
        <button>😢</button>
        <button>😭</button>
        <button>😮‍💨</button>
        <button>😤</button>
        <button>😠</button>
        <button>😡</button>
        <button>🤬</button>
        <button>🤯</button>
        <button>😳</button>
        <button>🥵</button>
        <button>🥶</button>
        <button>😱</button>
        <button>😨</button>
        <button>😰</button>
        <button>😥</button>
        <button>😓</button>
        <button>🫣</button>
        <button>🤗</button>
        <button>🫡</button>
        <button>🤔</button>
        <button>🫢</button>
        <button>🤭</button>
        <button>🤫</button>
        <button>🤥</button>
        <button>😶</button>
        <button>😶‍🌫️</button>
        <button>😐</button>
        <button>😑</button>
        <button>😬</button>
        <button>🫨</button>
        <button>🫠</button>
        <button>🙄</button>
        <button>😯</button>
        <button>😦</button>
        <button>😧</button>
        <button>😮</button>
        <button>😲</button>
        <button>🥱</button>
        <button>😴</button>
        <button>🤤</button>
        <button>😪</button>
        <button>😵</button>
        <button>😵‍💫</button>
        <button>🫥</button>
        <button>🤐</button>
        <button>🥴</button>
        <button>🤢</button>
        <button>🤮</button>
        <button>🤧</button>
        <button>😷</button>
        <button>🤒</button>
        <button>🤕</button>
        <button>🤑</button>
        <button>🤠</button>
        <button>😈</button>
        <button>👿</button>
        <button>👹</button>
        <button>👺</button>
        <button>🤡</button>
        <button>💩</button>
        <button>👻</button>
        <button>💀</button>
        <button>☠️</button>
        <button>👽</button>
        <button>👾</button>
        <button>🤖</button>
        <button>🎃</button>
        <button>😺</button>
        <button>😸</button>
        <button>😹</button>
        <button>😻</button>
        <button>😼</button>
        <button>😽</button>
        <button>🙀</button>
        <button>😿</button>
        <button>😾</button>
    </div>
}